services:
  nvim:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: vimmer
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
        NVIM_CONF_URL: ${NVIM_CONF_URL}

    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - nvim:/home/vimmer
      # - type: bind
      #   source: "<your-ssh-key>" #your github ssh key dir
      #   target: "/root/.ssh"
    networks:
      - backend
      - frontend
    ports:
      - 6497:6497 # QWERTY配列を左から順に数えただけ

volumes:
  nvim:

networks:
  backend: # ファイルシステムを同期するため
    driver: bridge
  frontend: # Neovimにリモートアクセスを許可するため
    driver: bridge
