services:
  nvim:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: vimmer
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
        NVIM_CONF_URL: ${NVIM_CONF_URL}

    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - type: volume # 例えばインストールしたLSPなどを保持しておくために必要。
        source: nvim
        target: /home/vimmer
      - type: volume
        source: shared_volume
        target: /home/vimmer/usr
      # - type: bind
      #   source: "<your-ssh-key>" #your github ssh key dir
      #   target: "/root/.ssh"
    ports:
      - 6497:6497 # QWERTY配列を左から順に数えただけ

volumes:
  nvim:
  shared_volume:
    name: ${VOLUME}
    external: true
